image: docker:edge

services:
 - docker:dind

before_script:
  - apk -U add git

stages:
- buildPeerTube
- buildZ2pdf
- buildphpFuelPHP
- buildetherpad
- buildGrav
- buildPresentator
- buildStandardfile
- buildStandardnotes
- buildReverseNginx
- pushOnGithub
 
buildReverseNginx:
  stage: buildReverseNginx
  tags:
    - docker
    - build
  script:
    - sh nginx/builder.sh   

buildZ2pdf:
  stage: buildZ2pdf
  tags:
    - docker
    - build
  script:
    - sh z2pdf/builder.sh

buildphpFuelPHP:
  stage: buildphpFuelPHP
  tags:
    - docker
    - build
  script:
    - sh php/fuelphp/builder.sh

buildetherpad:
  stage: buildetherpad
  tags:
    - docker
    - build
  script:
    - sh etherpad/builder.sh

buildGrav:
  stage: buildGrav
  tags:
    - docker
    - build
  script:
    - sh php/grav/builder.sh

buildPresentator:
  stage: buildPresentator
  tags:
    - docker
    - build
  script:
    - sh presentator/builder.sh

buildStandardfile:
  stage: buildStandardfile
  tags:
    - docker
    - build
  script:
    - sh standardfile/builder.sh

buildStandardnotes:
  stage: buildStandardnotes
  tags:
    - docker
    - build
  script:
    - sh standardnotes/builder.sh

buildPeerTube:
  stage: buildPeerTube
  tags:
    - docker
    - build
  script:
    - sh peertube/builder.sh

pushOnGithub:
  stage: pushOnGithub
  tags:
    - push
  script:
    - echo "push on docker"
    - git push --mirror https://$GITHUB_TOKEN@github.com/Dryusdan/Dockerfiles.git
