image: gitlab/dind
stages:
- buildZ2pdf
- buildNginx
- buildphpFuelPHP
- buildetherpad

before_script:
  - docker info
  
    
buildZ2pdf:
  stage: buildZ2pdf
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/z2pdf:latest z2pdf/
    - docker push registry.dryusdan.fr/dryusdan/z2pdf:latest
    - docker rmi registry.dryusdan.fr/dryusdan/z2pdf:latest
    
buildNginx:
  stage: buildNginx
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/nginx:ipv6 nginx/
    - docker push registry.dryusdan.fr/dryusdan/nginx:ipv6
    - docker rmi registry.dryusdan.fr/dryusdan/nginx:ipv6
    
buildphpFuelPHP:
  stage: buildphpFuelPHP
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/php:fuelPHP php/fuelphp/
    - docker push registry.dryusdan.fr/dryusdan/php:fuelPHP
    - docker rmi registry.dryusdan.fr/dryusdan/php:fuelPHP
    

buildetherpad:
  stage: buildetherpad
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/etherpad etherpad/
    - docker push registry.dryusdan.fr/dryusdan/etherpad
    - docker rmi registry.dryusdan.fr/dryusdan/etherpad
