image: docker:edge


services:
 - docker:dind

stages:
- buildZ2pdf
- buildphpFuelPHP
- buildetherpad
- buildGrav
- buildPresentator
- buildStandardfile
- buildStandardnotes
- buildPeerTube
- buildReverseNginx
- pushOnGithub
 
buildReverseNginx:
  stage: buildReverseNginx
  tags:
    - docker
    - build
  script:
    - apk -U add git
    - sh nginx/builder.sh
    - docker push registry.dryusdan.fr/dryusdan/reverse-nginx:latest
    - docker rmi registry.dryusdan.fr/dryusdan/reverse-nginx:latest    

buildZ2pdf:
  stage: buildZ2pdf
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/z2pdf:latest z2pdf/
    - docker push registry.dryusdan.fr/dryusdan/z2pdf:latest
    - docker rmi registry.dryusdan.fr/dryusdan/z2pdf:latest
    
buildphpFuelPHP:
  stage: buildphpFuelPHP
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/php:fuelPHP php/fuelphp/
    - docker push registry.dryusdan.fr/dryusdan/php:fuelPHP
    - docker rmi registry.dryusdan.fr/dryusdan/php:fuelPHP

buildetherpad:
  stage: buildetherpad
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/etherpad etherpad/
    - docker push registry.dryusdan.fr/dryusdan/etherpad
    - docker rmi registry.dryusdan.fr/dryusdan/etherpad

buildGrav:
  stage: buildGrav
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/php:grav php/grav
    - docker push registry.dryusdan.fr/dryusdan/php:grav
    - docker rmi registry.dryusdan.fr/dryusdan/php:grav

buildPresentator:
  stage: buildPresentator
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/presentator presentator
    - docker push registry.dryusdan.fr/dryusdan/presentator
    - docker rmi registry.dryusdan.fr/dryusdan/presentator

buildStandardfile:
  stage: buildStandardfile
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/standardfile standardfile
    - docker push registry.dryusdan.fr/dryusdan/standardfile
    - docker rmi registry.dryusdan.fr/dryusdan/standardfile

buildStandardnotes:
  stage: buildStandardnotes
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/standardnotes standardnotes
    - docker push registry.dryusdan.fr/dryusdan/standardnotes
    - docker rmi registry.dryusdan.fr/dryusdan/standardnotes

buildPeerTube:
  stage: buildPeerTube
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/peertube peertube
    - docker push registry.dryusdan.fr/dryusdan/peertube
    - docker rmi registry.dryusdan.fr/dryusdan/peertube

pushOnGithub:
  stage: pushOnGithub
  tags:
    - push
  script:
    - apk -U add git
    - echo "push on docker"
    - git push --mirror https://$GITHUB_TOKEN@github.com/Dryusdan/Dockerfiles.git
