image: gitlab/dind
stages:
- buildNginx
- buildphpFuelPHP
- buildetherpad
- buildGrav
- buildMonitoring
- buildCachethq
- buildPresentator
- pushOnGithub

before_script:
  - docker info
  
buildNginx:
  stage: buildNginx
  tags:
    - docker
    - build
  script:
    - sh nginx/builder.sh
    - docker push registry.dryusdan.fr/dryusdan/nginx:ipv6
    - docker rmi registry.dryusdan.fr/dryusdan/nginx:ipv6
    
buildphpFuelPHP:
  stage: buildphpFuelPHP
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/php:fuelPHP php/fuelphp/
    - docker push registry.dryusdan.fr/dryusdan/php:fuelPHP
    - docker rmi registry.dryusdan.fr/dryusdan/php:fuelPHP
    

buildetherpad:
  stage: buildetherpad
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/etherpad etherpad/
    - docker push registry.dryusdan.fr/dryusdan/etherpad
    - docker rmi registry.dryusdan.fr/dryusdan/etherpad

buildGrav:
  stage: buildGrav
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/php:grav php/grav
    - docker push registry.dryusdan.fr/dryusdan/php:grav
    - docker rmi registry.dryusdan.fr/dryusdan/php:grav

buildMonitoring:
  stage: buildMonitoring
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/cachet-monitoring cachet-monitoring
    - docker push registry.dryusdan.fr/dryusdan/cachet-monitoring
    - docker rmi registry.dryusdan.fr/dryusdan/cachet-monitoring

buildCachethq:
  stage: buildCachethq
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/cachethq --build-arg cachet_ver=2.3.10 cachethq
    - docker push registry.dryusdan.fr/dryusdan/cachethq
    - docker rmi registry.dryusdan.fr/dryusdan/cachethq

buildPresentator:
  stage: buildPresentator
  tags:
    - docker
    - build
  script:
    - docker build -t registry.dryusdan.fr/dryusdan/presentator presentator
    - docker push registry.dryusdan.fr/dryusdan/presentator
    - docker rmi registry.dryusdan.fr/dryusdan/presentator

pushOnGithub:
  stage: pushOnGithub
  tags:
    - push
  script:
    - echo "push on docker"
    - git push --mirror https://$GITHUB_TOKEN@github.com/Dryusdan/Dockerfiles.git
