image: docker:edge

services:
 - docker:dind

before_script:
  - apk -U add git openssh-client
  - mkdir -p /root/.ssh
  - touch ~/.ssh/id_rsa
  - touch ~/.ssh/id_rsa.pub
  - base64 -d $GITHUB_PRIVATE_KEY > ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa 
  - chmod 600 ~/.ssh/id_rsa
  - touch ~/.ssh/known_hosts
  - ssh-keyscan github.com >> ~/.ssh/known_hosts

stages:
- buildPeerTube
- buildZ2pdf
- buildphpFuelPHP
- buildetherpad
- buildGrav
- buildPresentator
- buildStandardfile
- buildStandardnotes
- buildReverseNginx
- pushOnGithub
 
buildReverseNginx:
  stage: buildReverseNginx
  tags:
    - docker
    - build
  script:
    - sh nginx/builder.sh   

buildZ2pdf:
  stage: buildZ2pdf
  tags:
    - docker
    - build
  script:
    - sh z2pdf/builder.sh

buildphpFuelPHP:
  stage: buildphpFuelPHP
  tags:
    - docker
    - build
  script:
    - sh php/fuelphp/builder.sh

buildetherpad:
  stage: buildetherpad
  tags:
    - docker
    - build
  script:
    - sh etherpad/builder.sh

buildGrav:
  stage: buildGrav
  tags:
    - docker
    - build
  script:
    - sh php/grav/builder.sh

buildPresentator:
  stage: buildPresentator
  tags:
    - docker
    - build
  script:
    - sh presentator/builder.sh

buildStandardfile:
  stage: buildStandardfile
  tags:
    - docker
    - build
  script:
    - sh standardfile/builder.sh

buildStandardnotes:
  stage: buildStandardnotes
  tags:
    - docker
    - build
  script:
    - sh standardnotes/builder.sh

buildPeerTube:
  stage: buildPeerTube
  tags:
    - docker
    - build
  script:
    - sh peertube/builder.sh
    - cd /
    - git clone git@github.com:Chocobozzz/PeerTube-Docker.git
    - git clone git@git.drycat.fr:2022/Dryusdan/Dockerfiles.git
    - cp -R /Dockerfiles/peertube /PeerTube-Docker/production
    - cd /Peertube-Docker/
    - git add production/
    - git commit -m "update production"
    - git push

pushOnGithub:
  stage: pushOnGithub
  tags:
    - push
  script:
    - echo "push on docker"
    - git push --mirror https://$GITHUB_TOKEN@github.com/Dryusdan/Dockerfiles.git
