image: docker:edge

services:
 - docker:dind

before_script:
  - apk -U add git

stages:
- buildPeerTube
- buildZ2pdf
- buildphpFuelPHP
- buildetherpad
- buildGrav
- buildPresentator
- buildStandardfile
- buildStandardnotes
- buildReverseNginx
- buildKresus
- pushOnGithub
 
buildReverseNginx:
  stage: buildReverseNginx
  tags:
    - docker
    - build
  script:
    - sh nginx/builder.sh   

buildKresus:
  stage: buildKresus
  tags:
    - docker
    - build 
  script:  
    - sh kresus/builder.sh


buildZ2pdf:
  stage: buildZ2pdf
  tags:
    - docker
    - build
  script:
    - sh z2pdf/builder.sh

buildphpFuelPHP:
  stage: buildphpFuelPHP
  tags:
    - docker
    - build
  script:
    - sh php/fuelphp/builder.sh

buildetherpad:
  stage: buildetherpad
  tags:
    - docker
    - build
  script:
    - sh etherpad/builder.sh

buildGrav:
  stage: buildGrav
  tags:
    - docker
    - build
  script:
    - sh php/grav/builder.sh

buildPresentator:
  stage: buildPresentator
  tags:
    - docker
    - build
  script:
    - sh presentator/builder.sh

buildStandardfile:
  stage: buildStandardfile
  tags:
    - docker
    - build
  script:
    - sh standardfile/builder.sh

buildStandardnotes:
  stage: buildStandardnotes
  tags:
    - docker
    - build
  script:
    - sh standardnotes/builder.sh

buildPeerTube:
  stage: buildPeerTube
  tags:
    - docker
    - build
  script:
    - sh peertube/builder.sh

pushOnGithub:
  stage: pushOnGithub
  tags:
    - push
  script:
    - apk add openssh-client
    - git config --global user.email "dryusdan@dryusdan.fr"
    - git config --global user.name "Dryusdan"
    - mkdir -p /root/.ssh
    - eval $(ssh-agent -s)
    - touch ~/.ssh/id_rsa
    - echo $GITHUB_PRIVATE_KEY | base64 -d | ssh-add -
    - echo $GITHUB_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - touch ~/.ssh/known_hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - echo "push on github"
    - git push --mirror git@github.com:Dryusdan/Dockerfiles.git
